#pragma once

#define ANSI_FG_BLACK "\x1B[30m"
#define ANSI_FG_RED "\x1B[31m"
#define ANSI_FG_GREEN "\x1B[32m"
#define ANSI_FG_YELLOW "\x1B[33m"
#define ANSI_FG_BLUE "\x1B[34m"
#define ANSI_FG_MAGENTA "\x1B[35m"
#define ANSI_FG_CYAN "\x1B[36m"
#define ANSI_FG_WHITE "\x1B[37m"
#define ANSI_FG_BRIGHT_BLACK "\x1B[90m"
#define ANSI_FG_BRIGHT_RED "\x1B[91m"
#define ANSI_FG_BRIGHT_GREEN "\x1B[92m"
#define ANSI_FG_BRIGHT_YELLOW "\x1B[93m"
#define ANSI_FG_BRIGHT_BLUE "\x1B[94m"
#define ANSI_FG_BRIGHT_MAGENTA "\x1B[95m"
#define ANSI_FG_BRIGHT_CYAN "\x1B[96m"
#define ANSI_FG_BRIGHT_WHITE "\x1B[97m"

#define ANSI_BG_BLACK "\x1B[40m"
#define ANSI_BG_RED "\x1B[41m"
#define ANSI_BG_GREEN "\x1B[42m"
#define ANSI_BG_YELLOW "\x1B[43m"
#define ANSI_BG_BLUE "\x1B[44m"
#define ANSI_BG_MAGENTA "\x1B[45m"
#define ANSI_BG_CYAN "\x1B[46m"
#define ANSI_BG_WHITE "\x1B[47m"
#define ANSI_BG_BRIGHT_BLACK "\x1B[100m"
#define ANSI_BG_BRIGHT_RED "\x1B[101m"
#define ANSI_BG_BRIGHT_GREEN "\x1B[102m"
#define ANSI_BG_BRIGHT_YELLOW "\x1B[103m"
#define ANSI_BG_BRIGHT_BLUE "\x1B[104m"
#define ANSI_BG_BRIGHT_MAGENTA "\x1B[105m"
#define ANSI_BG_BRIGHT_CYAN "\x1B[106m"
#define ANSI_BG_BRIGHT_WHITE "\x1B[107m"

#define ANSI_RESET "\x1B[0m"